version: "3.1"

services:
  db:
    image: postgres
    container_name: station_db
    restart: always
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: docker
    ports:
      - 8306:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
