version: "3.1"

services:
  db:
    image: postgres
    container_name: station_db
    restart: always
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./init-user.sh:/etc/mysql/conf.d/init-user.sh
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: docker
    ports:
      - 8306:3006

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
