version: "3.1"

services:
  db:
    image: registry.hub.docker.com/library/postgres
    restart: always
    # TODO
    # volumes:
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: docker
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080